import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
// Providers
import { ReactQueryClientProvider } from "@/components/providers/ReactQueryClientProvider";
import { AuthProvider } from "@/components/providers/AuthProvider";

//modularise these below
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <AuthProvider>
            {children}

            <Toaster position="bottom-center" richColors />
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
